# Generated by Django 4.1.2 on 2024-07-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_carrito_creado_en_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
